---
title: "preimier league"
output: html_document
date: "2024-11-09"
---
```{r}
library(tidyverse)
library(dplyr)
```
```{r}
#reading match data
MatchData_2021_22 <-read_csv("C:/Users/DELL/Downloads/data/2021-22_data.csv")
MatchData_2022_23 <- read_csv("C:/Users/DELL/Downloads/data/2022-23_data.csv")
MatchData_2023_24 <- read_csv("C:/Users/DELL/Downloads/data/2023-24_data.csv")
```
```{r}
#Reading Match events
# Reading and adding Season column to match events data for each season
MatchEvents_2021 <- read_csv("C:/Users/DELL/Downloads/data/2021-22_match id home away and event type.csv") %>%
  mutate(Season = "2021-22")

MatchEvents_2022 <- read_csv("C:/Users/DELL/Downloads/data/2022-23_match id home away and event type.csv") %>%
  mutate(Season = "2022-23")

MatchEvents_2023 <- read_csv("C:/Users/DELL/Downloads/data/2023-24_match id home away and event type.csv") %>%
  mutate(Season = "2023-24")

```
```{r}

# Add season column and calculate total goals per match
MatchData_2021_22 <- MatchData_2021_22 %>% mutate(season = "2021-22", total_goals = home_team_goals + away_team_goals)
MatchData_2022_23 <- MatchData_2022_23 %>% mutate(season = "2022-23", total_goals = home_team_goals + away_team_goals)
MatchData_2023_24 <- MatchData_2023_24 %>% mutate(season = "2023-24", total_goals = home_team_goals + away_team_goals)
```
```{r}
#Combining data for match data of all season
combined_matchdata <- bind_rows(MatchData_2021_22, MatchData_2022_23, MatchData_2023_24)
```
```{r}
#Combining data for match events of all season
combined_matchevents <- bind_rows(MatchEvents_2021, MatchEvents_2022, MatchEvents_2023)
```
```{r}
#data cleaning

##For Match data 
class(combined_matchdata$`45+`)
class(combined_matchdata$`90+`)
class(combined_matchdata$Match_Id)
```
```{r}
class(combined_matchdata$match_date)
```
```{r}
combined_matchdata$match_date <- as.Date(combined_matchdata$match_date)
```
```{r}
class(combined_matchdata$home_team_goals)
class(combined_matchdata$away_team_goals)
class(combined_matchdata$attendance)
```
```{r}
combined_matchdata$attendance <- suppressWarnings(as.numeric(combined_matchdata$attendance))
```
```{r}
class(combined_matchdata$attendance)
```



```{r}
##For Match Events

class(combined_matchevents$Match_Id)
class(combined_matchevents$Home_Away)
class(combined_matchevents$Event_Minute)
```
```{r}
class(combined_matchevents$Event_Type)
```
```{r}
unique(combined_matchevents$Event_Type)
```
```{r}
### matching Event_type
combined_matchevents <- combined_matchevents %>%
  mutate(Event_Type = case_when(
    Event_Type == "Second Yellow Card (Red Card)" ~ "Red Card",
    TRUE ~ Event_Type
  ))
```


```{r}
# Calculate cumulative goals for each season
combined_matchdata <- combined_matchdata %>%
  group_by(season) %>%
  arrange(Match_Id) %>%
  mutate(cumulative_goals = cumsum(total_goals)) %>%
  ungroup()
```
```{r}
## Cumulative goals plot
ggplot(combined_matchdata, aes(x = Match_Id, y = cumulative_goals, color = season)) +
  geom_line(size = 1) +
  labs(title = "Cumulative Goals Across Seasons", x = "Match Sequence (Match ID)", y = "Cumulative Goals") +
  scale_color_manual(values = c("2021-22" = "blue", "2022-23" = "green", "2023-24" = "red")) +
  theme_minimal()
```


```{r}
# Calculate total goals per season
total_goals_per_season <- combined_matchevents %>%
  filter(Event_Type %in% c("Goal", "Own Goal", "label.penalty.scored")) %>%
  group_by(Season) %>%
  summarise(Total_Goals = n())
```
```{r}
## Total goals bar plot

ggplot(total_goals_per_season, aes(x = Season, y = Total_Goals, fill = Season)) +
  geom_bar(stat = "identity") +
  labs(title = "Total Goals per Season", x = "Season", y = "Total Goals") +
  scale_fill_manual(values = c("2021-22" = "blue", "2022-23" = "green", "2023-24" = "red"))
```
```{r}
# Mean, Sd, Median for goals per season
Mean_goals_2021_22 <- mean(MatchData_2021_22$total_goals)
Mean_goals_2021_22
Std_goals_2021_22 <- sd(MatchData_2021_22$total_goals)
Std_goals_2021_22
Median_goals_2021_22 <- median(MatchData_2021_22$total_goals)
Median_goals_2021_22

Mean_goals_2022_23 <- mean(MatchData_2022_23$total_goals)
Mean_goals_2022_23
Std_goals_2022_23 <- sd(MatchData_2022_23$total_goals)
Std_goals_2022_23
Median_goals_2022_23 <- median(MatchData_2022_23$total_goals)
Median_goals_2022_23

Mean_goals_2023_24 <- mean(MatchData_2023_24$total_goals)
Mean_goals_2023_24
Std_goals_2023_24 <- sd(MatchData_2023_24$total_goals)
Std_goals_2023_24
Median_goals_2023_24 <- median(MatchData_2023_24$total_goals)
Median_goals_2023_24
```

```{r}
ggplot(MatchData_2021_22, aes(x = `90+`)) +
  geom_histogram(fill = "blue", color = "black", binwidth = 1, boundary = 0.5) +
  labs(title = "Distribution of extra time after 90 minutes 21-22", x = "Minutes", y = "Number of Matches") +
  scale_x_continuous(limits = c(1, 15), breaks = 1:15)

ggplot(MatchData_2022_23, aes(x = `90+`)) +
  geom_histogram(fill = "green", color = "black", binwidth = 1, boundary = 0.5) +
  labs(title = "Distribution of extra time after 90 minutes 22-23", x = "Minutes", y = "Number of Matches") +
  scale_x_continuous(limits = c(1, 15), breaks = 1:15)

ggplot(MatchData_2023_24, aes(x = `90+`)) +
  geom_histogram(fill = "red", color = "black", binwidth = 1, boundary = 0.5) +
  labs(title = "Distribution of extra time after 90 minutes 23-24", x = "Minutes", y = "Number of Matches") +
  scale_x_continuous(limits = c(1, 15), breaks = 1:15)

```


```{r}
mean_extra_time_21_22 <- mean(MatchData_2021_22$`90+`)
mean_extra_time_21_22
std_extra_time_21_22 <- sd(MatchData_2021_22$`90+`)
std_extra_time_21_22

mean_extra_time_22_23 <- mean(MatchData_2022_23$`90+`)
mean_extra_time_22_23
std_extra_time_22_23 <- sd(MatchData_2022_23$`90+`)
std_extra_time_22_23

mean_extra_time_23_24 <- mean(MatchData_2023_24$`90+`)
mean_extra_time_23_24
std_extra_time_23_24 <- sd(MatchData_2023_24$`90+`)
std_extra_time_23_24
```

```{r}
# Goals after 90 mintues
Goals_after_90 <- combined_matchevents %>%
  filter(Event_Minute >= 90 & Event_Type %in% c("Goal", "label.penalty.scored"))
```
```{r}
##Box plot Goals after 90 mintues
ggplot(Goals_after_90, aes(x = Season, y = Event_Minute, fill = Season)) +
  geom_boxplot() +
  labs(title = "Distribution of Goals Scored After 90 Minutes", x = "Season", y = "Event Minute") + theme_minimal() +
  scale_fill_manual(values = c("2021-22" = "blue", "2022-23" = "green", "2023-24" = "red")) +
  theme(legend.position = "none")
```


```{r}
## Mean and Sd of goals time after 90 
goals_count_after_90_2021_22 <- filter(Goals_after_90, Season == "2021-22")
mean_goals_time_after_90_21_22 <- mean(goals_count_after_90_2021_22$Event_Minute)
mean_goals_time_after_90_21_22
std_goals_time_after_90_21_22 <- sd(goals_count_after_90_2021_22$Event_Minute)
std_goals_time_after_90_21_22

goals_count_after_90_2022_23 <- filter(Goals_after_90, Season == "2022-23")
mean_goals_time_after_90_22_23 <- mean(goals_count_after_90_2022_23$Event_Minute)
mean_goals_time_after_90_22_23
std_goals_time_after_90_22_23 <- sd(goals_count_after_90_2022_23$Event_Minute)
std_goals_time_after_90_22_23

goals_count_after_90_2023_24 <- filter(Goals_after_90, Season == "2023-24")
mean_goals_time_after_90_23_24 <- mean(goals_count_after_90_2023_24$Event_Minute)
mean_goals_time_after_90_23_24
std_goals_time_after_90_23_24 <- sd(goals_count_after_90_2023_24$Event_Minute)
std_goals_time_after_90_23_24 
```

```{r}
#Total cards per season
Cards_per_season <- filter(combined_matchevents, Event_Type %in% c("Yellow Card", "Red Card"))
```
```{r}
#Total cards per season
Yellow_Cards_per_season <- filter(combined_matchevents, Event_Type %in% c("Yellow Card"))
```

```{r}
### Create the bar plot for total cards
ggplot(Yellow_Cards_per_season, aes(x = Season, fill = Event_Type)) +
  geom_bar(position = "dodge") +
  labs(title = "Distribution of Yellow Cards by Season", x = "Season", y = "Number of Cards") +
  theme_minimal() +
  scale_fill_manual(values = c("Yellow Card" = "yellow")) +
  theme(legend.position = "left")
```
```{r}
#Total cards per season
Red_Cards_per_season <- filter(combined_matchevents, Event_Type %in% c("Red Card"))
```

```{r}
### Create the bar plot for total cards
ggplot(Red_Cards_per_season, aes(x = Season, fill = Event_Type)) +
  geom_bar(position = "dodge") +
  labs(title = "Distribution of Red Cards by Season", x = "Season", y = "Number of Cards") +
  theme_minimal() +
  scale_fill_manual(values = c("Red Card" = "red")) +
  theme(legend.position = "left")
```

```{r}
### Create the bar plot for total cards
ggplot(Cards_per_season, aes(x = Season, fill = Event_Type)) +
  geom_bar(position = "dodge") +
  labs(title = "Distribution of Cards Overall by Season", x = "Season", y = "Number of Cards") +
  theme_minimal() +
  scale_fill_manual(values = c("Yellow Card" = "yellow", "Red Card" = "red")) +
  theme(legend.position = "left")

```


```{r}
# Filter for goals in the 2023-24 season
Goals_2023_24 <- combined_matchevents %>%
  filter(Season == "2023-24" & Event_Type %in% c("Goal", "Own Goal", "label.penalty.scored"))
```
```{r}
## Create a histogram of goals scored per minute for the 2023-24 season
ggplot(Goals_2023_24, aes(x = Event_Minute)) +
  geom_histogram(binwidth = 1, fill = "red", color = "black") +
  labs(title = "Distribution of Goals Scored per Minute (2023-24 Season)", 
       x = "Match Minute", 
       y = "Count of Goals") +
  theme_minimal()
```

```{r}
## Filter for goals scored after the 90th minute in the 2023-24 season
Goals_after_90_2023_24 <- combined_matchevents %>%
  filter(Season == "2023-24" & Event_Minute > 90 & Event_Type %in% c("Goal", "Own Goal", "label.penalty.scored"))
```
```{r}
##  Histogram for goals scored after the 90th minute
ggplot(Goals_after_90_2023_24, aes(x = Event_Minute)) +
  geom_histogram(binwidth = 1, fill = "red", color = "black") +
  labs(title = "Distribution of Goals Scored After 90 Minutes (2023-24 Season)", 
       x = "Extra Time Minute", 
       y = "Count of Goals") +
  theme_minimal() +
  scale_x_continuous(breaks = seq(91, max(Goals_after_90_2023_24$Event_Minute), by = 5))
```
```{r}

Substitution_after_90 <- combined_matchevents %>%
  filter(Event_Type == "Substitution" & Event_Minute > 90 & Season %in% c("2022-23", "2023-24"))

# Create the bar plot for substitutions after the 90th minute by season
ggplot(Substitution_after_90, aes(x = Season, fill = Season)) +
  geom_bar(position = "dodge") +
  labs(title = "Distribution of Substitutions After 90 Minutes by Season", 
       x = "Season", 
       y = "Number of Substitutions (After 90 Minutes)") +
  theme_minimal() +
  scale_fill_manual(values = c("2022-23" = "green", "2023-24" = "red")) +
  theme(legend.position = "left")
```


```{r}
# total playing time as 45+ & 90+ extra time
combined_matchdata <- combined_matchdata %>%
  mutate(total_playing_time = 90 + `90+` + `45+`)
```
```{r}
play_time_2021_22 <- filter(combined_matchdata, season == "2021-22")
Mean_play_time_2021_22 <- mean(play_time_2021_22$total_playing_time)
Mean_play_time_2021_22
std_play_time_2021_22 <- sd(play_time_2021_22$total_playing_time)
std_play_time_2021_22

play_time_2022_23 <- filter(combined_matchdata, season == "2022-23")
Mean_play_time_2022_23 <- mean(play_time_2022_23$total_playing_time)
Mean_play_time_2022_23
std_play_time_2022_23 <- sd(play_time_2022_23$total_playing_time)
std_play_time_2022_23

play_time_2023_24 <- filter(combined_matchdata, season == "2023-24")
Mean_play_time_2023_24 <- mean(play_time_2023_24$total_playing_time)
Mean_play_time_2023_24
std_play_time_2023_24 <- sd(play_time_2023_24$total_playing_time)
std_play_time_2023_24

# Plot for Average graph
mean_playing_time_df <- data.frame(
  season = c("2021-22", "2022-23", "2023-24"),
  mean_playing_time = c(Mean_play_time_2021_22, Mean_play_time_2022_23, Mean_play_time_2023_24)
)

ggplot(mean_playing_time_df, aes(x = season, y = mean_playing_time, fill = season)) +
  geom_bar(stat = "identity") +
  labs(x = "Season", y = "Mean Playing Time (minutes)") +
  theme_minimal() +
  scale_fill_manual(values = c("2021-22" = "blue", "2022-23" = "green", "2023-24" = "red")) +
  coord_cartesian(ylim = c(75, max(mean_playing_time_df$mean_playing_time) + 5))
```
```{r}
#Tables required for Stat Analysis
summary_table_count <- combined_matchevents %>%
  group_by(Match_Id, Season) %>%
  summarise(
    goal_count = sum(Event_Type %in% c("Goal", "label.penalty.scored", "Own Goal")),
    red_card_count = sum(Event_Type == "Red Card"),                                 
    yellow_card_count = sum(Event_Type == "Yellow Card"),                           
    substitution_count = sum(Event_Type == "Substitution")                          
  )
```
```{r}
summary_table_count_90 <- combined_matchevents %>%
  filter(Event_Minute > 90) %>%  
  group_by(Match_Id, Season) %>%  
  summarise(
    goal_count = sum(Event_Type %in% c("Goal", "label.penalty.scored", "Own Goal")),
    red_card_count = sum(Event_Type == "Red Card"),                             
    yellow_card_count = sum(Event_Type == "Yellow Card"),                           
    substitution_count = sum(Event_Type == "Substitution")                          
  )
```
```{r}
# Step 1: Create a reference table with all Match_Id and Season combinations
all_combinations_2021 <- MatchEvents_2021 %>%
  distinct(Match_Id, Season)

# Step 2: Filter, group, summarize, and ensure all combinations are included
summary_2021_count_90 <- MatchEvents_2021 %>%
  filter(Event_Minute > 90) %>%  # Filter for events after the 90th minute
  group_by(Match_Id, Season) %>%  # Group by Match ID and Season
  summarise(
    goal_count = sum(Event_Type %in% c("Goal", "label.penalty.scored", "Own Goal")),
    red_card_count = sum(Event_Type == "Red Card"),                                 
    yellow_card_count = sum(Event_Type == "Yellow Card"),                           
    substitution_count = sum(Event_Type == "Substitution"),                         
    .groups = "drop"
  ) %>%
  # Step 3: Join with all possible combinations to ensure completeness
  right_join(all_combinations_2021, by = c("Match_Id", "Season")) %>%
  # Step 4: Replace NA values with 0
  replace_na(list(
    goal_count = 0,
    red_card_count = 0,
    yellow_card_count = 0,
    substitution_count = 0
  ))
summary_2021_count_90 <- summary_2021_count_90 %>%
  arrange(Match_Id)
```

```{r}

all_combinations_2022 <- MatchEvents_2022 %>%
  distinct(Match_Id, Season)

summary_2022_count_90 <- MatchEvents_2022 %>%
  filter(Event_Minute > 90) %>%  
  group_by(Match_Id, Season) %>%  
  summarise(
    goal_count = sum(Event_Type %in% c("Goal", "label.penalty.scored", "Own Goal")),
    red_card_count = sum(Event_Type == "Red Card"),                                 
    yellow_card_count = sum(Event_Type == "Yellow Card"),                           
    substitution_count = sum(Event_Type == "Substitution"),                         
    .groups = "drop"
  ) %>%
  
  right_join(all_combinations_2022, by = c("Match_Id", "Season")) %>%
  
  replace_na(list(
    goal_count = 0,
    red_card_count = 0,
    yellow_card_count = 0,
    substitution_count = 0
  ))
summary_2022_count_90 <- summary_2022_count_90 %>%
  arrange(Match_Id)
```

```{r}
all_combinations_2023 <- MatchEvents_2023 %>%
  distinct(Match_Id, Season)

summary_2023_count_90 <- MatchEvents_2023 %>%
  filter(Event_Minute > 90) %>%  
  group_by(Match_Id, Season) %>% 
  summarise(
    goal_count = sum(Event_Type %in% c("Goal", "label.penalty.scored", "Own Goal")),
    red_card_count = sum(Event_Type == "Red Card"),                                 
    yellow_card_count = sum(Event_Type == "Yellow Card"),                           
    substitution_count = sum(Event_Type == "Substitution"),                         
    .groups = "drop"
  ) %>%

  right_join(all_combinations_2023, by = c("Match_Id", "Season")) %>%

  replace_na(list(
    goal_count = 0,
    red_card_count = 0,
    yellow_card_count = 0,
    substitution_count = 0
  ))
summary_2023_count_90 <- summary_2023_count_90 %>%
  arrange(Match_Id)
```

```{r}
all_combinations_events <- combined_matchevents %>%
  distinct(Match_Id, Season)

summary_events_count <- combined_matchevents %>%
  group_by(Match_Id, Season) %>%
  summarise(
    goal_count = sum(Event_Type %in% c("Goal", "label.penalty.scored", "Own Goal")),
    red_card_count = sum(Event_Type == "Red Card"),                                 
    yellow_card_count = sum(Event_Type == "Yellow Card"),                           
    substitution_count = sum(Event_Type == "Substitution"),                         
    .groups = "drop"
  ) %>%
  right_join(all_combinations_events, by = c("Match_Id", "Season")) %>%
  replace_na(list(
    goal_count = 0,
    red_card_count = 0,
    yellow_card_count = 0,
    substitution_count = 0
  ))
summary_events_count <- summary_events_count %>%
  arrange(Match_Id)
```

```{r}
all_combinations_2021 <- MatchEvents_2021 %>%
  distinct(Match_Id, Season)
summary_2021_count <- MatchEvents_2021 %>%
  group_by(Match_Id, Season) %>%
  summarise(
    goal_count = sum(Event_Type %in% c("Goal", "label.penalty.scored", "Own Goal")),
    card_count = sum(Event_Type %in% c("Red Card","Yellow Card")),
    substitution_count = sum(Event_Type == "Substitution"),        
    .groups = "drop"
  ) %>%
  right_join(all_combinations_2021, by = c("Match_Id", "Season")) %>%
  replace_na(list(
    goal_count = 0,
    card_count = 0,
    substitution_count = 0
  ))
summary_2021_count <- summary_2021_count %>%
  arrange(Match_Id)
```

```{r}
all_combinations_2022 <- MatchEvents_2022 %>%
  distinct(Match_Id, Season)
summary_2022_count <- MatchEvents_2022 %>%
  group_by(Match_Id, Season) %>%
  summarise(
    goal_count = sum(Event_Type %in% c("Goal", "label.penalty.scored", "Own Goal")),
    card_count = sum(Event_Type %in% c("Red Card","Yellow Card")),
    substitution_count = sum(Event_Type == "Substitution"),        
    .groups = "drop"
  ) %>%
  right_join(all_combinations_2022, by = c("Match_Id", "Season")) %>%
  replace_na(list(
    goal_count = 0,
    card_count = 0,
    substitution_count = 0
  ))
summary_2022_count <- summary_2022_count %>%
  arrange(Match_Id)
```

```{r}
all_combinations_2023 <- MatchEvents_2023 %>%
  distinct(Match_Id, Season)
summary_2023_count <- MatchEvents_2023 %>%
  group_by(Match_Id, Season) %>%
  summarise(
    goal_count = sum(Event_Type %in% c("Goal", "label.penalty.scored", "Own Goal")),
    card_count = sum(Event_Type %in% c("Red Card","Yellow Card")),
    substitution_count = sum(Event_Type == "Substitution"),        
    .groups = "drop"
  ) %>%
  right_join(all_combinations_2023, by = c("Match_Id", "Season")) %>%
  replace_na(list(
    goal_count = 0,
    card_count = 0,
    substitution_count = 0
  ))
summary_2023_count <- summary_2023_count %>%
  arrange(Match_Id)
```

```{r}
combined_summary_2122 <- bind_rows(summary_2021_count, summary_2022_count)
```

```{r}
combined_summary_2223 <- bind_rows(summary_2022_count, summary_2023_count)
```


```{r}
#CI of Total Goals Scored of two season.
Mean_of_goals_2021_2022 <- mean(combined_summary_2122$goal_count)
Std_of_goals_2021_2022 <- sd(combined_summary_2122$goal_count)
```
```{r}
Mean_of_goals_2021_2022
Std_of_goals_2021_2022
```
```{r}
CI_of_21_23 <- t.test(combined_summary_2122$goal_count, conf.level = 0.95) 
CI_of_21_23
```

```{r}
#Mean of Last season to goals.
Mean_of_goals_2023_24 <- mean(summary_2023_count$goal_count)
Mean_of_goals_2023_24
```

```{r}
# Table for cards.
card_2021_count_90 <- MatchEvents_2021 %>%
  filter(Event_Minute > 90) %>%
  group_by(Match_Id, Season) %>%
  summarise(
    goal_count = sum(Event_Type %in% c("Goal", "label.penalty.scored", "Own Goal")),
    card_count = sum(Event_Type %in% c("Red Card","Yellow Card")),
    substitution_count = sum(Event_Type == "Substitution"),        
    .groups = "drop"
  ) %>%
  right_join(all_combinations_2021, by = c("Match_Id", "Season")) %>%
  replace_na(list(
    goal_count = 0,
    card_count = 0,
    substitution_count = 0
  ))
card_2021_count_90 <- card_2021_count_90 %>%
  arrange(Match_Id)

card_2022_count_90 <- MatchEvents_2022 %>%
  filter(Event_Minute > 90) %>%
  group_by(Match_Id, Season) %>%
  summarise(
    goal_count = sum(Event_Type %in% c("Goal", "label.penalty.scored", "Own Goal")),
    card_count = sum(Event_Type %in% c("Red Card","Yellow Card")),
    substitution_count = sum(Event_Type == "Substitution"),        
    .groups = "drop"
  ) %>%
  right_join(all_combinations_2022, by = c("Match_Id", "Season")) %>%
  replace_na(list(
    goal_count = 0,
    card_count = 0,
    substitution_count = 0
  ))
card_2022_count_90 <- card_2022_count_90 %>%
  arrange(Match_Id)

combined_summary_2122_90 <- bind_rows(card_2021_count_90, card_2022_count_90)
```

```{r}
#Parameters Hypothesis for goals scored after 90+
Mean_of_goals_after_90_21_23 <- mean(combined_summary_2122_90$goal_count)
Mean_of_goals_after_90_21_23
```
```{r}
std_of_goals_after_90_21_23 <- sd(combined_summary_2122_90$goal_count)
std_of_goals_after_90_21_23

std_of_goals_after_90_23 <- sd(summary_2023_count_90$goal_count)
std_of_goals_after_90_23
```

```{r}
#Mean of Last season to 90+ goals.
Mean_of_goals_after_90_23 <- mean(summary_2023_count_90$goal_count)
Mean_of_goals_after_90_23
```

```{r}
#Hypothesis for goals scored after 90+
X_value_goals_after_90_23 <- c(summary_2023_count_90$goal_count)
Y_value_goals_after_90_23 <- c(combined_summary_2122_90$goal_count)
```

```{r}
library(BSDA)
```

```{r}
#Hypothesis for goals scored after 90+
z.test(x=X_value_goals_after_90_23, y=Y_value_goals_after_90_23, mu=0, sigma.x=0.5215199, sigma.y=0.3904923,alternative = "greater")
```

```{r}
# Parameters CI for Combined Cards for last two Season
Mean_of_cards_2021_2022 <- mean(combined_summary_2122$card_count)
Std_of_cards_2021_2022 <- sd(combined_summary_2122$card_count)
Mean_of_cards_2021_2022
Std_of_cards_2021_2022
```

```{r}
#CI for Combined Cards for last two Season
CI_of_cards_21_23 <- t.test(combined_summary_2122$card_count, conf.level = 0.95) 
CI_of_cards_21_23
```

```{r}
#paramters of cards of latest season.
Mean_of_cards_2023 <- mean(summary_2023_count$card_count)
Std_of_cards_2023 <- sd(summary_2023_count$card_count)
Mean_of_cards_2023
Std_of_cards_2023
```

```{r}
#paramters of Subs of latest season.
Mean_of_sub_2023 <- mean(summary_2023_count$substitution_count)
Mean_of_sub_2023
Std_of_sub_2023 <- sd(summary_2023_count$substitution_count)
Std_of_sub_2023
```

```{r}
#paramters of Subs of 2022 season.
Mean_of_sub_2022 <- mean(summary_2022_count$substitution_count)
Mean_of_sub_2022
Std_of_sub_2022 <- sd(summary_2022_count$substitution_count)
Std_of_sub_2022
```
```{r}
#CI of Subs of 2022 season.
CI_of_Subs_22_23 <- t.test(summary_2022_count$substitution_count, conf.level = 0.95) 
CI_of_Subs_22_23
```



```{r}
#paramters of Subs after 90+ of latest season.
Mean_of_sub_2023_90 <- mean(summary_2023_count_90$substitution_count)
Mean_of_sub_2023_90
Std_of_sub_2023_90 <- sd(summary_2023_count_90$substitution_count)
Std_of_sub_2023_90
```

```{r}
#paramters of Subs after 90+ of 2022 season.
Mean_of_sub_2022_90 <- mean(summary_2022_count_90$substitution_count)
Mean_of_sub_2022_90
Std_of_sub_2022_90 <- sd(summary_2022_count_90$substitution_count)
Std_of_sub_2022_90
```

```{r}
#CI of Subs after 90+ of 2022 season.
CI_of_Subs_22_23_90 <- t.test(summary_2022_count_90$substitution_count, conf.level = 0.95) 
CI_of_Subs_22_23_90
```


